name: On Push Actions
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'resources/java-runtime**'
jobs:
  updateremotepanel:
    name: Update Remote Panel
    if: github.repository == 'PhantomBot/PhantomBot'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: 'master'
    - name: Copy Files
      run: |
        rsync -rv --delete-during --progress resources/web/panel docs
        rsync -rv --delete-during --progress resources/web/common docs
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Updated the remote panel'
  parsecommandtags:
    name: Parse Command Tags on ubuntu-latest with Python 3.x
    if: github.repository == 'PhantomBot/PhantomBot'
    runs-on: ubuntu-latest
    needs: updateremotepanel
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: 'master'
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Execute Script
      run: python3 development-resources/parse_transformers.py
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Updated the custom command tags guide'
  parseconsolecommands:
    name: Parse Console Commands on ubuntu-latest with Python 3.x
    if: github.repository == 'PhantomBot/PhantomBot'
    runs-on: ubuntu-latest
    needs: parsecommandtags
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: 'master'
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Execute Script
      run: python3 development-resources/parse_consolecommands.py
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Updated the console commands guide'
  parsebotproperties:
    name: Parse Bot Properties on ubuntu-latest with Python 3.x
    if: github.repository == 'PhantomBot/PhantomBot'
    runs-on: ubuntu-latest
    needs: parseconsolecommands
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: 'master'
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Execute Script
      run: python3 development-resources/parse_botproperties.py
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Updated the bot properties guide and json file'
  javadoc:
    name: Generate JavaDoc on ubuntu-latest
    if: github.repository == 'PhantomBot/PhantomBot'
    runs-on: ubuntu-latest
    needs: parsebotproperties
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        ref: 'master'
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Set up Ant
      run: sudo apt-get install ant
    - name: Retrieve Libs with Ant
      run: ant -noinput -buildfile build.xml ivy-retrieve
    - name: JavaDoc with Ant
      run: ant -noinput -buildfile build.xml javadoc
    - name: Execute Script
      run: python3 development-resources/clean_javadoc.py
    - name: Copy Files
      run: |
        rsync -rv --delete-during --progress dist/javadoc docs
    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v13
      id: verify-changed-files
      with:
        files: |
          docs/javadoc/**
          !docs/javadoc/*.zip
    - name: Commit Changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Updated the JavaDoc'
